name: Deploy Stack
on:
  push:
    branches:
    - main
concurrency:
  group: airflow-dependencies
  cancel-in-progress: false
jobs:
  deploy:
    runs-on:
    - self-hosted
    - mlops-stack
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Deploy
      env:
        TARGET_DIR: ${{ vars.TARGET_DIR }}
      run: |
        rsync -rtlv --delete --exclude-from=.gitignore . "$TARGET_DIR" || true
        cd "$TARGET_DIR"
        ./setup.sh
