name: Deploy Stack
on:
  push:
    branches:
    - main
concurrency:
  group: airflow-dependencies
  cancel-in-progress: false
jobs:
  deploy:
    runs-on:
    - self-hosted
    - mlops-stack
    steps:
    - name: Pull latest changes
      run: |
        git fetch origin main
        git reset --hard origin/main
    - name: Deploy
      run: |
        ./setup.sh
